### ISSUE TITLE
USER STORY: Sorting categories

### ISSUE THREAD

**Issue by siobhanlgorman** [siobhanlgorman/knits-and-pieces#15]
As a **shopper** I want to be able to  **sort a specific category of products** so that I can **find the best priced product within a specific category or sort the products alphabetically within a category**

**Acceptance Criteria**:
-  1: User can select how to sort products from navigation
-  2: Badges display the categories viewed and can be clicked to narrow down categories
-  3: User can click on options in sort box to sort categories

**Tasks**:
- [ ] Task 1: Create sort box with options
- [ ] Task 2: Add sorting code in template
- [ ] Task 3: Add function in views
- [ ] Task 4: Add javascript for sort box
