### ISSUE TITLE
USER STORY: Payment information

### ISSUE THREAD

**Issue by siobhanlgorman** [siobhanlgorman/knits-and-pieces#22]
As a **shopper** I want to be able to  **easily enter my payment information** so that I can **checkout quickly and easily**

**Acceptance Criteria**:
-  1: User clicks on checkout to complete payment form
-  2:  Success message visible on completion of payment process
-  3:

**Tasks**:
- [ ] Task 1: Install and set up stripe
- [ ] Task 2: Create template for payent form
- [ ] Task 3: Set up webhooks to check success/errors in payment process
- [ ] Task 4:
