### ISSUE TITLE
USER STORY: Purchase: Email confirmation

### ISSUE THREAD

**Issue by siobhanlgorman** [siobhanlgorman/knits-and-pieces#25]
As a **shopper** I want to be able to **receive email confirmation of my purchase** so that I can **have a record of my purchases**

**Acceptance Criteria**:
-  1: User receives email confirmation in terminal with name, order information
-  2:
-  3:

**Tasks**:
- [ ] Task 1: Create templates for emails
- [ ] Task 2: Add code to settings.py
- [ ] Task 3: Add code to webhook handler after payment created
- [ ] Task 4:
