### ISSUE TITLE
USER STORY: Administration: add a product

### ISSUE THREAD

**Issue by siobhanlgorman** [siobhanlgorman/knits-and-pieces#26]
As an **store owner** I want to be able to **add a product** so that I can **add new products to my store**

**Acceptance Criteria**:
-  1: Administrator can click on Add a Product link in navbar to bring up add a product form
-  2: Administrator can add a product, save by clicking add product button and view product on site
-  3:

**Tasks**:
- [ ] Task 1: Create product form
- [ ] Task 2: Write view
- [ ] Task 3: Write url
- [ ] Task 4: Create template for form
