### ISSUE TITLE
USER STORY: Administration: edit and update a product

### ISSUE THREAD

**Issue by siobhanlgorman** [siobhanlgorman/knits-and-pieces#27]
As a **store owner** I want to be able to **be able to edit and update a product** so that I can **change information relating to a product**

**Acceptance Criteria**:
-  1: Adminstrator can click on edit in product detail page to open up edit form
-  2: Adminstrator can edit and then click update product to save changes
-  3:

**Tasks**:
- [ ] Task 1: Create view code for edit product
- [ ] Task 2: Create button links on template
- [ ] Task 3: Add urls 
- [ ] Task 4: Add post method to form view
