### ISSUE TITLE
USER STORY: Administration: delete a product

### ISSUE THREAD

**Issue by siobhanlgorman** [siobhanlgorman/knits-and-pieces#28]
As a **store owner** I want to be able to **delete a product** so that I can **remove items no longer for sale**

**Acceptance Criteria**:
-  1: Administrator can click on delete in product detail page to delete a product
-  2:
-  3:

**Tasks**:
- [ ] Task 1: Create view
- [ ] Task 2: Create url
- [ ] Task 3: Add delete button in product detail template
- [ ] Task 4:
