### ISSUE TITLE
USER STORY: About Page

### ISSUE THREAD

**Issue by siobhanlgorman** [siobhanlgorman/knits-and-pieces#6]
As a **shopper** I want to be able to  **view more information about the store** so that I can **increase my confidence that the store is genuine, trustworthy and reliable**

**Acceptance Criteria**:
-  1: About page visible and linked in navigation

**Tasks**:
- [ ] Task 1: Create About page
- [ ] Task 2: Add navigation links
- [ ] Task 3: Add link button to Shop
- [ ] Task 4:
